# code: language=ansible
# AryaOS UUID service.
#
# Copyright Sensors & Signals LLC https://www.snstac.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Upload UUID util script
  ansible.builtin.copy:
    src: "{{ shared_files }}/aryaos/set_uuid.sh"
    dest: /usr/local/sbin
    mode: "0755"

- name: Set UUID util service
  ansible.builtin.copy:
    src: "{{ shared_files }}/aryaos/set_uuid.service"
    dest: /lib/systemd/system
    mode: "0644"

- name: Enable UUID util service
  ansible.builtin.systemd:
    name: set_uuid
    enabled: true
    state: started
    daemon_reload: true
