site_name: AirTAK
site_url: https://airtak.rtfd.io/
repo_url: https://github.com/snstac/airtak
site_description: AirTAK Documentation
site_author: Greg Albrecht <gba@snstac.com>
copyright: Copyright Sensors & Signals LLC https://www.snstac.com/

theme:
  name: material
  highlightjs: true

plugins:
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - toc:
      permalink: True
