version: '2'

services:
 mqtt_broker:
  image: "eclipse-mosquitto"
  volumes:
   - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
   - ./mosquitto_certs:/etc/mosquitto/certs/
  ports:
   - "1883:1883"
  hostname: mqtt_broker
  restart: always
  network_mode: "bridge"
  mem_limit: 256m #optional, limit maximum memory usage to 256 Mbyte
  mem_reservation: 64M #optional, in case of low memory on the host, limit memory usage to 64 Mbyte
  cpus: 1 # optional guarantee at least 100% CPU time of one CPU core
