# code: language=ansible
#
# Copyright Sensors & Signals LLC https://www.snstac.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Include fa
  ansible.builtin.include_tasks: fa.yml

- name: Include tar1090
  ansible.builtin.include_tasks: tar1090.yml

- name: Include dump978
  ansible.builtin.include_tasks: dump978.yml

- name: Include readsb
  ansible.builtin.include_tasks: readsb.yml

- name: Include adsbcot
  ansible.builtin.include_tasks: adsbcot.yml

# Create a task that installs the osmocom-rtl-sdr udev rules
- name: Install osmocom-rtl-sdr udev rules
  ansible.builtin.copy:
    src: "{{ shared_files }}/adsbcot/osmocom-rtl-sdr.rules"
    dest: /etc/udev/rules.d/
    mode: "0644"
  # notify: reload udev rules
  when: ansible_virtualization_type != 'docker'
