# code: language=ansible
# Installs dump1090.
#
# Copyright Sensors & Signals LLC https://www.snstac.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


- name: Upload tar1090 install script
  ansible.builtin.copy:
    src: "{{ shared_files }}/adsbcot/tar1090-install.sh"
    dest: /usr/src
    mode: "0755"

- name: Install tar1090
  ansible.builtin.command:
    cmd: /usr/src/tar1090-install.sh
    creates: /etc/default/tar1090
  become: true

