version: '2'

services:
 dronescout:
  image: "docker.dronescout.co:5045/dronescout_x86_64" #use dronescout_arm64 for ARM64 platforms
  volumes:
   - ./config:/config # folder with config files: dronescout.conf, wlan_channels.conf and license file
  hostname: dronescout
  restart: always
  privileged: true
  network_mode: "host"
  mem_limit: 128m #optional, limit maximum memory usage to 128 Mbyte
  mem_reservation: 32M #optional, in case of low memory on the host, limit memory usage to 32 Mbyte
  cpus: 0.5 # optional guarantee at least 50% CPU time of one CPU core
  entrypoint: ./config/start.sh
