# code: language=ansible
# main.yml
#
# Copyright Sensors & Signals LLC https://www.snstac.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present

- name: Update apt cache for Docker
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker packages.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ lookup('file', '../01-install/00-packages').split('\n') }}"
  tags:
    - packages

- name: Add node-red to docker group
  ansible.builtin.user:
    name: node-red
    groups: docker

- name: Add ansible to docker group
  ansible.builtin.user:
    name: ansible
    groups: docker
